# tap
tap "k1low/tap"
tap "ktr0731/evans"
tap "omuomugin/tap"

# brew
brew "curl"
brew "deno"
brew "docker"
brew "evans"
brew "git-delta"
brew "graphviz"
brew "httpie"
brew "lcov"
brew "plantuml"
brew "postgresql"
brew "redis"
brew "starship"
brew "tesseract-lang"
brew "trafilatura"
brew "tree"
brew "zsh-completions"
brew "zsh-autosuggestions"

brew "k1low/tap/octocov"
brew "k1low/tap/runn"

# apps
cask_args appdir: "/Applications"
cask "1password"
cask "ghostty"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "monitorcontrol"
cask "raycast"
cask "slack"
cask "visual-studio-code"
cask "zoom"
