# Brewfile
tap "omuomugin/tap"
tap "knqyf263/pet"

brew "java"
brew "curl"
brew "docker"
brew "fzf"
brew "ghq"
brew "go"
brew "graphviz"
brew "httpie"
brew "jq"
brew "yq"
brew "mysql"
brew "nodenv"
brew "peco"
brew "plantuml"
brew "postgresql"
brew "rbenv"
brew "redis"
brew "sbt"
brew "starship"
brew "tmux"
brew "tree"
brew "yarn"
brew "gh"
brew "awscli"
brew "k6"
brew "terraform"
brew "zsh-autosuggestions"
brew "pet"
bewq "kubectx"

# -> self created tool
brew "castit"

cask_args appdir: "/Applications"
cask "1password"
cask "raycast"
cask "docker"
cask "google-chrome"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "slack"
cask "visual-studio-code"
cask "zoom"
