# Don't print a new line at the start of the prompt
add_newline = false

[cmd_duration]
min_time = 1_000 # millisecond
show_notifications = true 

[git_branch]
symbol = ""

[git_status]
disabled = true

[time]
disabled = false
use_12hr = true
format = '[$time]($style) '

[kubernetes]
disabled = false